language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

addons:
  coverity_scan:
    project:
      name: "JorgeCastilloPrz/KotlinAndroidArchitecture"
      description: ""
    notification_email: jorge.castillo.prz@gmail.com
    branch_pattern: develop

script:
  ./gradlew detektCheck build -PmarvelPublicKey="\"whatever\"" -PmarvelPrivateKey="\"whatever\""

