language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

addons:
  coverity_scan:
    project:
      name: "JorgeCastilloPrz/KotlinAndroidArchitecture"
      description: ""
    notification_email: jorge.castillo.prz@gmail.com
    build_command_prepend: "Kotlin playground to investigate some kind-of-functional approaches for architecture of Android apps."
    build_command:   "./gradlew detektCheck build"
    branch_pattern: develop

script:
  ./gradlew detektCheck build -PmarvelPublicKey=whatever -PmarvelPrivateKey=whatever
